### ISSUE TITLE
Why Companies should migrate to Swift

### ISSUE THREAD

**Issue by iyadagha** [swift-berlin/swift-berlin.github.io#21]
name: Mohamed Iyad Tamer Agha
company: Immobilien Scout
title: Why Companies should migrate to Swift
abstract: a lightning talk for swift.berlin#15 to share some thoughts about migrating Objective-C projects to Swift.
twitter: @iyadagha
audience: iOS developers and iOS team managers

**Comment by JensRavens** [comment]
Hey Mohamed, thanks for proposing a talk. Could you please add some info as described in our [speakers guide](http://swift.berlin/how-to-become-a-speaker/)?

**Comment by JensRavens** [comment]
Hey Iyad,
I didn't notice you've changed your post. I'll add you to the lineup. Thanks!
