### ISSUE TITLE
Reference Github on home 

### ISSUE THREAD

**Issue by marciok** [swift-berlin/swift-berlin.github.io#9]
There is no reference about this repo on the website. 

I think it would be good to have a message like: _"Hey, do you want to propose a talk? Open an issue on our repo with your idea, etc..."_ on the home page

Or just add a "Fork me" on the top.

**Comment by JensRavens** [comment]
We should add the propose talk part under speakers if there are less then 3 speakers. Also adding the fork me banner is a nice idea.

Is there a fork-me graphic/banner that doesn't look completely hideous?

**Comment by marciok** [comment]
@JensRavens I don't think so, maybe we can start with a ["classic one"](https://github.com/blog/273-github-ribbons) and design our own later.
WDYT?
